title:"SUE Study" 
theme: just-the-docs
url: https://sue-23.github.io
aux_links:
  Template Repository: https://github.com/sue-23/sue-23.github.io.git 
plugins:
  - jekyll-seo-tag
search_enabled: true

