title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sue-23.github.io

aux_links:
  Template Repository: https://github.com/sue-23/sue-23.github.io.git 
